### ISSUE TITLE
ROS2 CH06 Understanding parameters

### ISSUE THREAD

**Issue by SilasYoome** [SilasYoome/blog#37]
parameter是node的配置值，可以將parameter視為node的設定值。
node可以將parameter儲存為整數(integers)、浮點數(floats)、布林數(booleans)、字串(strings)和列表(list)
在ROS2中每個node會維護自己的parameter

# 前提
會繼續使用turtlesim package，使用以下兩個指令來執行
```
ros2 run turtlesim turtlesim_node
ros2 run turtlesim turtle_teleop_key
```

# ros2 param list
查看歸屬於node的parameter

```
ros2 param list
```
將可以看見node的命名空間(namespace)，```/teleop_turtle```和```/turtlesim```，在其之後的是每個node的parameter
```
/teleop_turtle:
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  scale_angular
  scale_linear
  use_sim_time
/turtlesim:
  background_b
  background_g
  background_r
  qos_overrides./parameter_events.publisher.depth
  qos_overrides./parameter_events.publisher.durability
  qos_overrides./parameter_events.publisher.history
  qos_overrides./parameter_events.publisher.reliability
  use_sim_time
```
每個node都有個parameter ```use_sim_time```，並不是turtlesim獨有的parameter
根據它們的名字，像是```/turltesim```的parameter用來決定turtlesim視窗背景顏色，用RGB數值表達
要得到parameter的type，則可以使用```ros2 param get```

# 3. ros2 param get
若要顯示parameter的type和當前數值，可以使用這命令
```
ros2 param get <node_name> <parameter_name>
```

看看``/turtlesim```的parameter```background_g```的當前數值吧
```
ros2 param get /turtlesim background_g
```

將會回傳下方的數值
```
Integer value is : 86
```

現在可以知道```background_g```的type是整數值
如果用同樣的指令去查看```background_r```和```background_b```，則會得到```69```和```255```這兩個數值

# 4. ros2 param set
修改parameter的當前數值，使用以下的指令
```
ros2 param set <node_name> <parameter_name> <value>
```

試著來修改背景顏色
```
ros2 param set /urtlesim background_r 150
```

將會看到終端回傳以下訊息
```
set parameter successful
```

就可以看見turtlesim視窗背景顏色改變
使用```set```指令設定parameter數值，是只限於此會話框，而不是永久變更。但可以江浙設定儲存，並在下自啟動node時充新載入

# 5. ros2 param dump
若想查看所有parameter的現在數值，可以使用以下指令
```
ros2 param dump <node_name>
```
在預設的情況下，該指令會將結果顯示在終端上
但也可以將參數儲存到檔案中以供以後只用
若要將目前的```/turtlesim```參數配置儲存到檔案```turtlesim.yaml```，要輸入以下指令
```
ros2 param dump /turtlesim > /turtlesim.yaml
```
就能夠在當前終端執行的工作目錄中找到一個新文件，如果開啟此文件，將可看到以下內容
```
/turtlesim:
  ros__parameters:
    background_b: 255
    background_g: 86
    background_r: 150
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
```
果將來想用相同的parameter數值載入node，轉儲parameter就會派上用場

# 6. ros2 param load
